name: 2023-05-01-hsf-india-tutorial
channels:
  - conda-forge
dependencies:
  - awkward
  - cudatoolkit
  - cupy
  - cxx-compiler
  - fsspec
  - h5py
  - hepunits
  - hist
  - ipympl
  - jax
  - jaxlib
  - jupyterlab-deck
  - jupyterlab-mathjax3
  - lz4
  - matplotlib
  - numba
  - numexpr
  - numpy
  - pandas
  - particle
  - pyarrow
  - pybind11
  - python
  - python-xxhash
  - uproot
  - vector
  - zstandard
  - zstd
