name: 2023-05-01-hsf-india-tutorial
channels:
  - conda-forge
  - nvidia
dependencies:
  - cudatoolkit==11.3.1
  - cupy==12.0.0
  - cxx-compiler==1.5.2
  - jupyterlab-deck==0.1.3
  - jupyterlab-mathjax3==4.3.0
  - python==3.10.11
  - pip
  - nvcc_linux-64
  - pytables
  - python-xxhash
  - root
  - zstandard
  - zstd
  - pip:
    - awkward
    - clang-tools
    - fsspec
    - h5py
    - hepunits
    - hist
    - ipympl
    - jax
    - jaxlib
    - lz4
    - matplotlib
    - numba
    - numexpr
    - numpy
    - pandas
    - particle
    - protobuf
    - pyarrow
    - pybind11
    - scikit-learn
    - tensorflow-gpu==2.11.0
    - uproot
    - vector
