name: 2023-12-18-hsf-india
channels:
  - conda-forge
  - nvidia/label/cuda-11.7.0
dependencies:
  - cudatoolkit==11.7.0
  - cudatoolkit-dev
  - cuda==11.7.0
  - cuda-version==11.7.0
  - cuda-libraries==11.7.0
#  - cupy==12.0.0
  - cudnn
  - nvidia-ml
#  - cxx-compiler==1.6.0
  - gxx==11.4.0
  - gcc==11.4.0
  - jupyterlab-deck==0.1.3
  - jupyterlab-mathjax3==4.3.0
  - python==3.10.11
  - pip
  - nvcc_linux-64==11.7
  - pytables
  - python-xxhash
  - root [--clobber]
  - zstandard
  - zstd
  - pip:
    - awkward
    - clang-tools
    - cupy-cuda11x
    - fsspec
    - h5py
    - hepunits
    - hist
    - ipympl
    - jax
    - jaxlib
    - lz4
    - matplotlib
    - numba
    - numexpr
    - numpy
    - pandas
    - particle
    - protobuf
    - nvidia-tensorrt
    - pyarrow
    - pybind11
    - scikit-learn
    # tensorflow 2.11.0 has errors I can not resolve..
    - tensorflow-gpu==2.10.0
    - uproot
    - vector
