name: 2023-05-01-hsf-india-tutorial
channels:
  - conda-forge
  - nvidia
dependencies:
  - cudatoolkit
  - pip
  - nvcc_linux-64
  - cudatoolkit
  - cupy
  - cxx-compiler
  - jupyterlab-deck
  - jupyterlab-mathjax3
  - python
  - pip:
    - awkward
    - clang-tools
    - fsspec
    - h5py
    - hepunits
    - hist
    - ipympl
    - jax
    - jaxlib
    - lz4
    - matplotlib
    - numba
    - numexpr
    - numpy
    - pandas
    - particle
    - protobuf
    - pyarrow
    - pybind11
    - pytables
    - python-xxhash
    - root
    - scikit-learn
    - tensorflow-gpu
    - uproot
    - vector
    - zstandard
    - zstd
