#!/bin/bash

# # Allow drivers installed by the nvidia-driver-installer to be located
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/nvidia/lib64
# # Also, utilities like `nvidia-smi` are installed here
# export PATH=${PATH}:/usr/local/nvidia/bin

export LD_LIBRARY_PATH=${CONDA_PREFIX}/lib

# Also, utilities like `nvidia-smi` are installed here
export PATH=${PATH}:/usr/local/nvidia/bin

#export CUDA_HOME=/srv/conda/envs/notebook/
export CUDA_HOME=/usr/lib/x86_64-linux-gnu/

exec "$@"
