name: 2023-12-18-hsf-india
channels:
#  - nvidia/label/cuda-11.7.0
  - conda-forge
dependencies:
#  - cuda-version==11.7
#  - cudatoolkit==11.7.0
#  - cudatoolkit-dev==11.7.0
  - conda-libmamba-solver
  - libarchive
# - cuda
# a no op I think
#  - cuda-libraries-dev