name: hsf-india
channels:
  - defaults
  - nvidia/label/cuda-11.8.0
dependencies:
  - python=3.10
  - cuda=11.8
  - cudnn=8.9.2
  - cuda-nvcc
  - pip
#  - emacs
  - zstandard
  - zstd
  - clang-tools
  - fsspec
  - lz4
  - python-xxhash
#  - pytorch-gpu=2.0.0 -> seems to need to come after cuda
  - rapidsai::cudf=23.02.00
  - pip:
      - tensorflow==2.13
      - tensorrt
      - cupy-cuda11x
      - astunparse
      - awkward
      - dask
      - dask-awkward
      - distributed
      - h5py
      - hepunits
      - hist
      - ipympl
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - matplotlib
      - numba
      - numexpr
      - numpy
      - pandas
      - particle
      - protobuf
      - pyarrow
      - pycuda
      - pybind11
      - scikit-learn
      - tables
      - uproot
      - vector
      - mplhep
      - requests
      - aiohttp
      - jax[cpu]
      - graphviz
      - dask-labextension==6.2.0
      - torch=2.0.0
      - torchvision=2.0.0
      
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/'"
