name: tensorflow
channels:
  - defaults
  - nvidia/label/cuda-11.8.0
dependencies:
  - python=3.10
#  - cudatoolkit=11.8
#  - cudatoolkit-dev=11.8
#  - cudnn=8.1.0
  - cuda=11.8
  - cudnn=8.9.6
  - cuda-nvcc
  - pip
  - emacs
  - zstandard
  - zstd
  - clang-tools
  - fsspec
  - lz4
  - python-xxhash
  - pip:
      - tensorflow==2.13
      - cupy-cuda11x
      - astunparse
      - awkward
      - dask
      - dask-awkward
      - distributed
      - h5py
      - hepunits
      - hist
      - ipympl
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - matplotlib
      - numba
      - numexpr
      - numpy
      - pandas
      - particle
      - protobuf
      - pyarrow
      - pybind11
      - scikit-learn
      - tables
      - uproot
      - vector
  
      
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/lib/'"
