name: tensorflow
channels:
  - defaults
  - nvidia/label/cuda-11.7.1
dependencies:
  - python=3.10
  - cudatoolkit=11.7
  - cudnn=8.1.0
  - cuda-nvcc
  - pip
  - pip:
      - tensorflow==2.11.0
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/lib/'"
