name: tensorflow
channels:
  - defaults
  - nvidia/label/cuda-11.7.1
dependencies:
  - python
  - cudatoolkit=11.7
  - cudatoolkit-dev=11.7 
  - cudnn=8.1.0
  - cuda-nvcc
  - pip
  - emacs
  - zstandard
  - zstd
  - clang-tools
  - cupy
  - fsspec
  - lz4
  - python-xxhash
  - pip:
      - tensorflow-gpu==2.11.0
      - nvidia-pyindex
      - nvidia-tensorrt
      
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/lib/'"
