#!/bin/bash

rm /srv/conda/envs/notebook/README
export LD_LIBRARY_PATH=${CONDA_PREFIX}/lib
find / -name conda
which conda
/srv/conda/bin/conda install -n base libarchive -c main --force-reinstall
conda install --freeze-installed root==6.28.0 
